runtime: php81
env: standard

beta_settings:
  cloud_sql_instances: "gen-lang-client-0151389440:europe-west3:scandiweb"

handlers:
  - url: /.*
    script: public/index.php

env_variables:
  APP_ENV: "production"
  APP_DEBUG: "true"
  DB_DATABASE: "scandiweb_test"
  DB_USERNAME: "root"
  DB_PASSWORD: "mysql"
  DB_SOCKET: "/cloudsql/gen-lang-client-0151389440:europe-west3:scandiweb"
